language: python
python:
  - "3.6"

before_install:
  - pip install pytest pytest-cov coveralls flask

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment
  - pip install pytest pytest-cov coveralls

script:
  - py.test --cov-report term-missing:skip-covered --cov=geodepy geodepy/tests/

deploy:
  provider: pypi
  on:
    tags: true
  user:
    secure: U2kHuyRfeA3yCfeb3TeB54ASLOjkYSXwhliKAJPOFm6SbX5DLV6xHUQfqcArx1GxRLxn+7GADF+KGZRxGAVJNciciltWy6UVJCbDHtmGNUNkQVvdWwLnJlcWJK5WJa5q/B79u1fvnkPrEe15X0cLdoGZrh5UjjAl6YHGOM8LEoIVuXrlPUpH1Qp/mD7A9Ol368/wgvwcTNeTHo3qFPHNjsDI8JsyM107Y9eFYtzlkk9bceEFAsknaned1FBrvOPxmCnh6iIeV+mxm82WobwOp0OX07ctxB0jjJBtXY4MT0T0rIz4DzFt8FnIHmSSe7cxFLfAiveW2FHGs3p/0udG6fVHgyiOcdhXxiKj/3IW4IiMUlxCSye31Paldyrgj7DtbgjcsI5c22/WKeHp03Kd18PInJypprdjsaqmvhD6fgdFUt07lWH5d8SFL8FOSHfwCCr6L8SMOb7Vkv53jegp9Twli3G+2wyUphDtiWQLaVvcK1ADEHi8XGQy1TbJ7UESmWZdl1aHDRMHrEUKMCbPryosP9y0laAXejERHPQ7yQI76XAv0lwQbgnDaphhDrubK0eJI5IFHo3BzCi+dWsnLaj2RklGPMnaSy0XwGYcfk4NHkMR3lP4bqt7YVa1nXUCn/etDT+pJCvLnpEixM5ROwIvJrHN/WJZ6DrUxaIaydA=
  password:
    secure: nXqUOnZo0Gn0xmsfzRDIz0xHAyUJeRPn2YI8Xij7GbcnDpFcW+QfX8g2jZsHKzy2YhS+aUGqk2Ii4n0Q609Kc3vNjR28bdx01bJBtAfgOgTJwQkA8TxnJG5suy0fPPHwc7QJU11r4daHqDX5x0a4Hhg0J8t64QksVY7ENxwH/phXeRD03t0ERutgjulFbU+KLSuEOJogbyl/WHJlfUa+D+jFiVXyb5LGi+F9caxVM1D7GFBC3ameaz/hn+rWELaeqy4YlgsiuzBmWXxVBbuJQ0Ev09Y48wpnIUkSiQFFyagE+INBFxs1BPZ6Z4wYilpiVbASJeygCwyEupcAF8KgaksiPJSzFRQtmF+E6n5dhuJx9X0a+6rqQUUwPljCEajbkob3bICK9Lfm2QqyX7HZ8djIa57fSnHab6Kzy8akMUxOmGQexsez4smuGyhAFRSsDJ1pOx+hyOeUvQJ44u/QPSumO+Bvjke34anWIDs3hXdOFATFgYDBlTvlh8yv+yd/u77JHH6zSS+mf9jDpxN5EOtZu78Y2zxPObk912xmo/QyZa1Ox6PuEEV0hBEAvZiUsDJh3/07fRzHDFSdnKz0Od6UJy+eHT40bZCW6gBsPj0F8VghoTMIWBkNxttoenBYoYV/mcw/no26yjOpS6jzENNulhXSTR1T9HGaPy8sz9Y=

after_success:
  - coveralls
